# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Workshop for Azure IoT
site_url: ""
repo_url: https://github.com/ks6088ts-labs/workshop-azure-iot
repo_name: ks6088ts-labs/workshop-azure-iot
nav:
  - Home: index.md
  - Scenarios:
    - 1. Azure IoT Hub Messaging: scenarios/1_azure_iot_hub_messaging.md
    - 2. Azure Event Grid Messaging: scenarios/2_azure_event_grid_messaging.md
theme:
  name: material
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  language: en
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ks6088ts/
    - icon: fontawesome/brands/github
      link: https://github.com/ks6088ts
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/ks6088ts
  analytics:
    provider: google
    property: G-0ZTKFXVQ5K
