name: test

on:
  push:
    branches:
      - "main"
      - "feature/**"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    strategy:
      matrix:
        platform:
          - "ubuntu-latest"
        python-version:
          - "3.10"
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Poetry
        shell: bash
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Run CI tests
        shell: bash
        run: |
          find . -maxdepth 1 -name "*.env.template" -exec sh -c 'cp "$1" "${1%.env.template}.env"' _ {} \;
          SKIP_TEST=True make ci-test
